# Include local machine custom settings.
[ -f ~/.bashrc.before ] && source ~/.bashrc.before

# ~/bin is prepended to the PATH, so we can override system utils, if needed.
# Relative bin is really helpful and drops most of the direnv cases I had. It
# also really help with Ruby projects as you can use the binstubs and not some
# arbitrary executable.
export PATH=~/bin:/usr/local/bin:$PATH

# Initialize rbenv before initializing the plugins. The bundler plugin needs
# the bundle executable available, so...
$(which rbenv &> /dev/null) || export PATH=~/.rbenv/bin:/~/.rbenv/shims:$PATH
$(which rbenv &> /dev/null) && eval "$(rbenv init -)"

# Initialize direnv for the bash
$(which direnv &> /dev/null) && eval "$(direnv hook bash)"

# Add color support for terminals pretending to be xterm.
[ $TERM = xterm ] && export TERM=xterm-256color

# Make sure we have a unicode capable LANG and LC_CTYPE so the unicode
# characters does not look like crap on OSX and other environments.
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# Help out programs spawning editors based on $EDITOR. The same for pagers,
# just use less for them.
export EDITOR=vim
export PAGER=less

# Source all of the aliases living in ~/.aliases.
[ -f ~/.aliases ] && source ~/.aliases

# Enable programmable completion features
[ -f /etc/bash_completion ] && ! shopt -oq posix && source /etc/bash_completion

# Include local machine custom settings.
[ -f ~/.bashrc.after ] && source ~/.bashrc.after
